{
    "concierge_id": "c19f796d-8fa4-4846-9a2f-af0065bb350f",
    "concierge_name": "cwlscassistant",
    "request_id": "requestId-bf3e9a3f-0f96-4219-88ae-24b072a4ce7c",
    "agent_name": "CreativeLSCToModeConnectorAgent",
    "agent_id": "68ba66bb4d31614de6d7d7ec",
    "agent_url": "https://ellm.creativeworkspace.ai/utility/creative-lsc-to-mode-connector-agent",
    "agent_arguments": {
        "user_query": "TRIGGER DOMAIN KNOWLEDGE AGENT:  TRIGGER DOMAIN KNOWLEDGE AGENT: What third-party library, internal module, or external service is used to perform the actual DOC/DOCX to PDF conversion in the Creative Workspace Backend?"
    },
    "chat_history": [],
    "question": "TRIGGER DOMAIN KNOWLEDGE AGENT:  TRIGGER DOMAIN KNOWLEDGE AGENT: What third-party library, internal module, or external service is used to perform the actual DOC/DOCX to PDF conversion in the Creative Workspace Backend?",
    "prompt": "",
    "modelType": "google",
    "preview_id": "6752bc9b-9612-40ec-bc16-8288989c6d35",
    "orchByPassed": False,
    "agent_config": {},
    "metadata": {
        "userName": "User",
        "userEmailId": "",
        "llm": "claude-3.5-sonnet",
        "remoteModeLLMAssistantDetails": {
            "WEBSOCKET_URL": "wss://ellm.creativeworkspace.ai/graphql",
            "organizationName": "techolution",
            "chatAssistantName": "appmodoncw",
            "selectedAIModel": "claude-35-sonnet",
            "userName": "User",
            "userEmailId": "",
            "userId": None,
            "query": "TRIGGER DOMAIN KNOWLEDGE AGENT:  TRIGGER DOMAIN KNOWLEDGE AGENT: What third-party library, internal module, or external service is used to perform the actual DOC/DOCX to PDF conversion in the Creative Workspace Backend?",
            "requestId": "requestId-bf3e9a3f-0f96-4219-88ae-24b072a4ce7c",
            "guestSessionId": "6752bc9b-9612-40ec-bc16-8288989c6d35",
            "chatPreviewId": "6752bc9b-9612-40ec-bc16-8288989c6d35",
            "sessionId": "techolution-cwlscassistant-0947b166-18ec-44ef-9725-c806c51d131a",
            "replyMessage": "",
            "notificationSessionId": "chat-session-b3232963-201b-4883-8737-4a89b0afa0ad",
            "images": None,
            "customMetaData": {
                "context": "{}",
                "branchName": "master",
                "userSelectedIntent": "",
                "userSelectedProjects": [
                    {
                        "taskId": "29b8c0bd-68b9-412b-af42-4bc56afe7f4f",
                        "databaseIndex": "appmodbf30e6faprod",
                        "project_name": "User Story Project",
                        "updated_at": "2025-11-18 15:44:16",
                        "status": "Completed",
                        "repo_url": "https://github.com/hrushik-reddy/extract-text-from-x",
                        "embedding_model": {
                            "model_name": "text-embedding-ada-002",
                            "model_type": "Azure OpenAI",
                        },
                    }
                ],
                "organization_name": "84lumber",
                "current_user_id": None,
                "github_token": "",
                "is_cw_flow": True,
                "send_metadata_to_orchestrator": True,
                "selectedProjectDetails": {
                    "assistantName": "appmodbf30e6faprod",
                    "project_name": "User Story Project",
                    "project_id": "0cc04d8a-0ab1-4c85-973a-ead0b3d5017d",
                    "task_id": "29b8c0bd-68b9-412b-af42-4bc56afe7f4f",
                    "current_user_id": None,
                    "owner_user_id": "",
                    "embedding_model": {
                        "model_name": "text-embedding-ada-002",
                        "model_type": "Azure OpenAI",
                    },
                    "datasource": "codebase",
                },
            },
            "textToSpeechAgentId": "68ac33a84d31614de6d36a01",
            "useTextToSpeech": True,
            "id": "a4fd7dd8-2b9c-480a-849b-972ba3c4be35",
            "isAudioAgent": True,
            "addUserMessageInChat": False,
            "isDocumentRetrieval": False,
            "multiAgentToggle": False,
            "selectedAgent": None,
            "runtimeAgents": None,
            "agentSettings": None,
            "customRootOrchestratorModelName": None,
            "customRootOrchestratorModelType": None,
            "customPrompt": "",
            "sameGuestSessionIdAsCentralAssistant": "true",
        },
        "currentActiveModeOfUser": "Appmod.AI Mode",
        "userId": None,
    },
    "agent_settings": {
        "embeddingColumnName": "mxbai_embed_large_v1_question_embeddings",
        "embeddingModel": "mxbai-embed-large-v1",
        "overrideAgentConfig": None,
        "rootOrchestratorConfig": {
            "useGuide": False,
            "dbIndexName": "techolution-cwlscassistant-agentGuide",
            "dbType": "alloydb",
            "guidePrompt": "You are strictly responsible...",
            "conflictPrompt": "You are an intelligent assistant...",
        },
    },
}
